### PR TITLE
OOMMF 2.0a3

### PR DESCRIPTION
**Pull request by lang-m**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lang-m** [comment]
@marijanbeg I am done with cleanup, so you could review everything.

**Comment by lang-m** [comment]
@marijanbeg I can't see any review/comments :(

**Comment by lang-m** [comment]
Neither refreshing the page nor logging out, closing the browser, and reopening did help. Maybe we can quickly discuss this tomorrow.

**Comment by marijanbeg** [comment]
@conda-forge-admin please rerender

**Comment by marijanbeg** [comment]
@conda-forge-admin please rerender

**Comment by marijanbeg** [comment]
Conclusions:
- We do need `xorg-libx11`
- We do NOT need `zlib`

`meta.yml` is now updated to reflect this.

**Comment by marijanbeg** [comment]
@lang-m, yes, I have been looking at this thread today. Great! This will simplify things a lot for us. Are patches still relevant for the new build (they are applied, but I do not know if they are still necessary)?

Please feel free to merge when you are ready.

**Comment by lang-m** [comment]
Assuming that build on CI is running as root my guess is that we still need the patches. I could try removing them if you think it would be beneficial.

**Pull request merged**
