### PR TITLE
Finish new compiler migration

### PR DESCRIPTION
**Pull request by minrk**
Trying to finish the upgrade to new compilers:

- bumped version to 2.0a1 because 2.0a0 cannot compile on recent versions of macOS
- symlink g++/clang++ because oommf config has some logic based on invalid assumptions about compiler executable names
- pass CXXFLAGS, LDFLAGS to oommf config via env, patches
- add some explicit links to z, m, stdc++ needed with stricter conda compilers

Windows builds will not be able to complete until the US government shutdown ends because math.nist.gov is down until then.

closes #8 
closes #7

### CODE REVIEW

**Comment by minrk** [comment]
All builds other than Windows worked, which can't run until the US gov't shutdown is over. I'd recommend landing this one as-is and opening an issue to rebuild Windows when math.nist.gov is back up.

**Comment by sergii-mamedov** [comment]
@minrk
Thank you so much for all your work. I am still trying to understand the changes you have made.

**Comment by minrk** [comment]
Most of the changes are passing the $CXX, $CXXFLAGS, $RANLIB, $LDFLAGS environment variables to a place where the oommf build system will find them. OOMMF doesn't respect standard environment variables, but they can be added to the platform configuration file. Then there's a little additional fiddling on linux because extra libraries need to be linked explicitly that aren't (libz, libm, libstdc++). These were found by identifying missing symbols in failed builds.

Then there's the CDT packages for x11 on linux, which are copied from the [tk recipe](https://github.com/conda-forge/tk-feedstock)

**Comment by sergii-mamedov** [comment]
@conda-forge-admin please rerender

**Comment by marijanbeg** [comment]
The link to precompiled files changed (pointing to `fangohr/oommf`). All builds pass now.

Thanks a lot @minrk! Much appreciated.

**Pull request merged**
