### PR TITLE
Build for osx_arm64 (second attempt)

### PR DESCRIPTION
**Pull request by lang-m**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lang-m** [comment]
@conda-forge-admin please re-render

**Comment by marijanbeg** [comment]
What is the meaning of `max_py_ver: '37'` line in `conda-forge.yml`? Is it maybe the maximum allowed Python version?

**Comment by lang-m** [comment]
Good question, I could not find it in the documentation here: https://conda-forge.org/docs/maintainer/conda_forge_yml.html

**Comment by marijanbeg** [comment]
I looked at the docs as well, but no success. I though about it because this might be causing environment-solving issues.

**Pull request closed without merging**
